import Head from 'next/head'

// Components
import { Text, Flex, Box, Img, Stack, Container, Icon } from '@chakra-ui/react'
import { FaPlay } from "react-icons/fa"

const userDescription = `Micah Walters is an online movement coach specializing in flexibility, acrobatics, and handstands. 
                        He has been a facilitator of physical training since 2006, working across numerous fields including gymnastics, ballet, yoga, hand-balancing, and most recently with special focus, flexibility. 
                        His firsthand experience as an athlete and professional artist, along with two decades of education and exploration, fuels his passion for coaching and passing on his knowledge.`

function LandingScreen ({ children }) {
  const instagramVideos = [1, 2, 3, 4, 5, 6]
  return (
    <>
        <Head>
          <title>Giscontorsion</title>
          <meta name="Giscontorsion" content="Generated by Nadia Gincoff" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Stack marginTop="0 !important" width="100%" height="100vh" marginbottom="10">
          <Flex position="absolute" height="40%" width="80%" alignItems="flex-end" justifyContent="flex-end" zIndex="-1">
              <Box>
                  <Text fontSize={{ base: `15px`, md: `25px`, lg: `45px`}} fontWeight="100" zIndex="1">LEADING EDGE</Text>
                  <Text fontSize={{ base: `15px`, md: `25px`, lg: `45px`}} fontWeight="100" zIndex="1">FLEXIBILITY TRAINING</Text>
              </Box>
          </Flex>
          <Box>
            <Img
              marginTop="0 !important"
              zIndex="-2"
              width="100%" 
              height="100vh"
              src='/assets/photos/pexels-cottonbro-5747777.jpg' 
              alt="background-home" 
              objectFit='cover'
            />
          </Box>
        </Stack>
        <Stack width={[ `100%`, `60%`]} alignItems="center" marginTop="5vh" flexDirection="column">
          <Img 
            marginY="5vh"
            width={[`70%`, `60%`]}
            height={[`50vh`, `100vh`]}
            src='/assets/photos/pexels-cottonbro-5770441.jpg' 
            alt="background-home" 
            objectFit='cover' 
          />
          <Box width={["350px", "450px"]} background="#FFFFFF" padding="8" position={{ md: "absolute" }} top={{ sm: `0`, md: "120vh" }} left={{ sm: `0`, md: "120vh"}} boxShadow={"0px 5px 20px 0px rgba(0,0,0,0.10)"}>
            <Text fontStyle="italic" textAlign="center">
              {userDescription}
            </Text>
          </Box>
        </Stack>
        <Stack width="100%">
          <Img 
            // marginY="5vh"
            // width={[`70%`, `60%`]}
            height={[`50vh`, `100vh`]}
            src='/assets/photos/pexels-cottonbro-5747790.jpg' 
            alt="background-home" 
            objectFit='cover' 
          />
        </Stack>
        <Stack width="100%" justifyContext="center" alignItems="center" paddingY="5" backgroundColor="yellow.50">
          <Text marginBottom="-5">Follow my journey!</Text>
          <Flex width={[`500px`, `700px`, `60%`]} height="30vh" justifyContent="space-evenly" alignItems={[`center`]} flexDirection="row" flexWrap="wrap" padding="5">
            {instagramVideos.map(instagramVideo => {
              return (
                <Flex 
                  width={[`20vh`, `25vh`, `15vh`]} 
                  height={[`20vh`, `25vh`,`15vh`]} 
                  key={instagramVideo} 
                  backgroundColor="blue" 
                  alignItems={`center`} 
                  flexDirection={[`column`]} 
                  justifyContent="center" 
                  marginY="5"
                  marginX={[0, 0, 2]}
                >
                  <FaPlay size="2em" />
                </Flex>
              )
            })}
          </Flex>
        </Stack>
    </>
  )
}

export default LandingScreen
