import Head from 'next/head';

// Components
import {
  Text, Flex, Box, Image, Stack, VStack, SimpleGrid,
} from '@chakra-ui/react';

import HomeScreen from './home'

function Home({ children }) {
  return (
    <Stack width="100%" justifyContent="space-between" flexDirection="column"> 
      <Head>
        <title>Giscontorsion</title>
        <meta name="Giscontorsion" content="Generated by Nadia Gincoff" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeScreen />
    </Stack>
  )
}

export default Home;